# Generated by Django 4.2 on 2023-08-17 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0002_alter_tweets_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=300, verbose_name='Mesaj')),
                ('image', models.FileField(upload_to='Comments', verbose_name='Dosya')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yorum Yapan')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.tweets', verbose_name='Tweet')),
            ],
        ),
    ]
