# Generated by Django 4.2 on 2023-08-17 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_tweetcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetcomments',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='user_app.tweets', verbose_name='Tweet'),
        ),
    ]
