# Generated by Django 4.2 on 2023-08-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_tweetcomments_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetcomments',
            name='image',
            field=models.FileField(blank=True, upload_to='Comments', verbose_name='Dosya'),
        ),
    ]
