# Generated by Django 4.2 on 2023-08-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_tweets_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetlikes',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='tweetlikes',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='likes',
        ),
        migrations.AddField(
            model_name='tweets',
            name='likes',
            field=models.ManyToManyField(to='user_app.tweetlikes', verbose_name='Beğenen Kişiler'),
        ),
    ]
