# Generated by Django 4.2 on 2023-08-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_remove_tweetlikes_liked_remove_tweetlikes_tweet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='likes',
            field=models.ManyToManyField(blank=True, to='user_app.tweetlikes', verbose_name='Beğenen Kişiler'),
        ),
    ]
