# Generated by Django 4.2 on 2023-08-22 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0012_tweetlikes_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50, verbose_name='Sebep')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('authorized', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yetkililer', to=settings.AUTH_USER_MODEL, verbose_name='Banlayan')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Banlanan')),
            ],
        ),
    ]
