# Generated by Django 4.2 on 2023-08-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_bannedusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetlikes',
            name='tweet',
        ),
    ]
