# Generated by Django 4.2 on 2023-08-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_tweetlikes_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='suspended',
            field=models.BooleanField(default=False, verbose_name='Askıda mı'),
        ),
    ]
